"""API error code registry package.

Re-exports all error code constants and the ``API_ERRORS`` description dict::

    from backend.api.errors import API_ERRORS, API_QUERY_NOT_FOUND
"""

from __future__ import annotations

from backend.api.errors.codes import (
    API_ERRORS,
    API_QUERY_NOT_FOUND,
    API_QUERY_STATUS_CONFLICT,
    API_QUERY_DUPLICATE,
    API_TASK_ID_INVALID,
    API_QUANT_INVALID_GRANULARITY,
    API_QUANT_INVALID_INSTRUMENT,
    API_QUANT_UNKNOWN_INDICATOR,
    API_QUANT_CONFIG_ERROR,
    API_QUANT_DB_FAILED,
    API_QUANT_NO_CURRENCY,
    API_REPORT_NOT_FOUND,
    API_THREAD_NOT_FOUND,
    API_THREAD_EMIT_INVALID_EVENT,
    API_THREAD_STATUS_INVALID,
    API_NODE_CACHE_INVALIDATE_DB_ERROR,
)

__all__ = [
    "API_ERRORS",
    "API_QUERY_NOT_FOUND",
    "API_QUERY_STATUS_CONFLICT",
    "API_QUERY_DUPLICATE",
    "API_TASK_ID_INVALID",
    "API_QUANT_INVALID_GRANULARITY",
    "API_QUANT_INVALID_INSTRUMENT",
    "API_QUANT_UNKNOWN_INDICATOR",
    "API_QUANT_CONFIG_ERROR",
    "API_QUANT_DB_FAILED",
    "API_QUANT_NO_CURRENCY",
    "API_REPORT_NOT_FOUND",
    "API_THREAD_NOT_FOUND",
    "API_THREAD_EMIT_INVALID_EVENT",
    "API_THREAD_STATUS_INVALID",
    "API_NODE_CACHE_INVALIDATE_DB_ERROR",
]
