# Governance errors
GOV_REGISTER_FAILED = "GOV_001"
GOV_DEREGISTER_FAILED = "GOV_002"
GOV_QUERY_FAILED = "GOV_003"
GOV_PUBLISH_END_FAILED = "GOV_004"
GOV_NODE_CANCEL_FAILED = "GOV_005"
GOV_TASK_CANCEL_FAILED = "GOV_006"
