"""Errors package for common_tasks."""

from backend.langgraph.models.common_tasks.errors.codes import (
    STATS_TASK_NO_DATA,
    STATS_TASK_PROVIDER_ERROR,
    STATS_TASK_CALC_ERROR,
    STATS_TASK_CORR_INSUFFICIENT_DATA,
    STATS_TASK_UNSUPPORTED_PERIOD,
    STATS_TASK_ERRORS,
)

__all__ = [
    "STATS_TASK_NO_DATA",
    "STATS_TASK_PROVIDER_ERROR",
    "STATS_TASK_CALC_ERROR",
    "STATS_TASK_CORR_INSUFFICIENT_DATA",
    "STATS_TASK_UNSUPPORTED_PERIOD",
    "STATS_TASK_ERRORS",
]
