/**
 * UI-side streaming error codes.
 *
 * Contains ONLY errors generated by the frontend streaming layer — browser
 * connectivity failures, SSE session state issues, and client-side timeouts.
 *
 * Backend-originated errors are NOT duplicated here; they travel inline with
 * SSE events as `error_code` + `error_description` fields on the `failed` and
 * `done` payloads, and can also be fetched in bulk via `GET /stream/errors`.
 *
 * Code prefix convention:
 *   TLS_         — browser TLS / certificate issues
 *   SSE_         — SSE connection management
 *   DONE_        — done-acknowledgement delivery
 *   QUERY_       — query submission / acknowledgement
 *   DRAIN_       — DoneConditionGuard drain lifecycle
 */

export const UI_STREAMING_ERRORS: Record<string, string> = {
  /**
   * The browser refused to open the SSE connection because the backend's TLS
   * certificate has not been accepted in this browser profile.  The user must
   * open the SSE origin URL directly and click "Accept" / "Proceed anyway".
   */
  TLS_CERT_NOT_ACCEPTED:
    "SSE connection refused — TLS certificate not accepted by this browser. " +
    "Open the backend origin in a new tab, accept the certificate, then retry.",

  /**
   * The backend task appears to have stopped without emitting a `done` event.
   * The stall detector surfaced this so the UI can mark the session as failed
   * rather than leaving it in an indefinite loading state.
   */
  SSE_STALL_ORPHAN:
    "The backend task stopped without sending a completion signal. " +
    "The session was automatically marked as failed by the stall detector.",

  /**
   * The SSE connection closed without a `done` event (e.g. network drop or
   * proxy timeout).
   */
  UNEXPECTED_SSE_CLOSE:
    "The SSE connection closed unexpectedly before the session completed. " +
    "This may be a network interruption — the page will attempt to reconnect.",

  /**
   * The done-ACK POST could not be delivered to the backend.  Non-fatal: the
   * session is still closed on the client side; the backend drain cycle will
   * clean up any leftover pending-notify entries on its own schedule.
   */
  DONE_ACK_SEND_FAILED:
    "Could not send the session completion acknowledgement to the backend. " +
    "The session is closed on the client side; the backend will self-clean.",

  /**
   * The query submission HTTP request failed (network error or non-2xx
   * response from the backend).
   */
  QUERY_SUBMIT_FAILED:
    "Failed to submit the query to the backend. " +
    "Check your network connection and try again.",

  /**
   * The query acknowledgement POST failed (e.g. on re-attach after a
   * stale-query recovery).
   */
  QUERY_ACK_FAILED:
    "The query acknowledgement could not be delivered to the backend. " +
    "The backend will retry delivery automatically via the drain cycle.",

  /**
   * The DoneConditionGuard drain window expired before all expected task
   * events were received.  The session was closed early to prevent an
   * indefinite loading state.
   */
  DRAIN_WINDOW_EXPIRED:
    "Session drain window expired before all task events were received. " +
    "The session was closed early to avoid an indefinite loading state.",
};
